# Импорт библиотек

In [2]:
import sys
import os

sys.path.append(os.path.abspath('lib'))

from filters_features_utils import FeatureSelector
from preprocessing_pipeline import create_combined_pipeline
from test_models import run_models_classifications
from common_utils import plot_target_distribution

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score, roc_curve
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.feature_selection import SelectKBest, mutual_info_classif, f_classif, RFE
from sklearn.decomposition import PCA
from scipy.stats import randint
import xgboost as xgb

# Считывание данных

In [4]:
df = pd.read_csv('data/processed.csv')
df.shape

(998, 214)

# Очистка таргета от выбросов

In [6]:
df = df[df['IC50, mM'] < 4000]

# Подготовка данных для эксперемента

In [8]:
combined_pipeline = create_combined_pipeline()
X = df.drop(columns=['IC50, mM', 'CC50, mM', 'SI'])
y1 = df['IC50, mM']
y2 = df['CC50, mM']
y3 = df['SI']
X_transformed = combined_pipeline.fit_transform(X)
df = pd.concat([X_transformed, y1, y2, y3], axis=1)

приоритет на recall, чтобы не упустить хорошее лекарство

In [10]:
X = df.drop(columns=['IC50, mM', 'CC50, mM', 'SI'])
y = df['IC50, mM'].apply(lambda v: 1 if v >= df['IC50, mM'].median() else 0)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f'Train dataset size: {X_train.shape}, {y_train.shape}')
print(f'Test dataset size: {X_test.shape}, {y_test.shape}')

Train dataset size: (796, 107), (796,)
Test dataset size: (200, 107), (200,)

In [19]:
run_models_classifications(X_train, X_test, y_train, y_test)

,Model,WA f1,accuracy,WA precision,WA recall,WA support,roc_auc
7,CatBoost,0.750352,0.750,0.751303,0.750,200.0,0.789495
9,AdaBoost,0.740366,0.740,0.741323,0.740,200.0,0.777195
3,Random Forest,0.720561,0.720,0.723424,0.720,200.0,0.794032
4,XGBoost,0.710408,0.710,0.711383,0.710,200.0,0.774473
5,Gradient Boosting,0.705334,0.705,0.705985,0.705,200.0,0.768828
6,LightGBM,0.700602,0.700,0.703440,0.700,200.0,0.776036
2,KNeighbors,0.696688,0.705,0.711982,0.705,200.0,0.729257
8,HistGradientBoosting,0.690621,0.690,0.694690,0.690,200.0,0.757183
0,Logistic Regression,0.680256,0.680,0.689261,0.680,200.0,0.773969
1,Decision Tree,0.670661,0.670,0.674670,0.670,200.0,0.670430
10,Gaussian,0.578944,0.630,0.681193,0.630,200.0,0.637312

# Фильтрация признаков

In [67]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.feature_selection import RFECV
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.datasets import make_classification


# Создание модели AdaBoostClassifier
ada = AdaBoostClassifier(n_estimators=50, algorithm='SAMME', random_state=42)

# Использование RFECV для отбора признаков
selector = RFECV(estimator=ada, step=1, cv=5, scoring='f1_weighted', n_jobs=-1)
selector.fit(X_train, y_train)

# Трансформация данных
X_train_selected = selector.transform(X_train)
X_test_selected = selector.transform(X_test)

# Обучение модели AdaBoostClassifier на отобранных признаках
ada.fit(X_train_selected, y_train)

# Предсказание на тестовой выборке
y_pred = ada.predict(X_test_selected)

# Вывод отчета классификации
report = classification_report(y_test, y_pred, output_dict=True)
print("Weighted Avg F1-Score:", report['weighted avg']['f1-score'])

# Вывод количества выбранных признаков
print("Количество выбранных признаков:", selector.n_features_)

Weighted Avg F1-Score: 0.6305205506984223
Количество выбранных признаков: 23

In [71]:
feature_importances = ada.feature_importances_

selected_feature_indices = selector.get_support(indices=True)
selected_feature_names = X.columns[selected_feature_indices]

importance_df = pd.DataFrame({
    'Feature': selected_feature_names,
    'Importance': feature_importances
}).sort_values(by='Importance', ascending=False)
importance_df

                     Feature  Importance
18        PEOE_VSA_variation    0.160931
15      EState_VSA_variation    0.143805
22                  balance4    0.091639
20          BCUT2D_variation    0.066933
16            VSA_EState_std    0.065849
13    fr_phenol_noOrthoHbond    0.061565
0              element_index    0.049427
9   NumSaturatedHeterocycles    0.049251
5    NumAliphaticCarbocycles    0.040477
1             MinEStateIndex    0.034190
7                 NumHDonors    0.032229
10              fr_C_O_noCOO    0.031708
11                    fr_NH2    0.030962
14               fr_priamide    0.029173
12                  fr_furan    0.027855
4                     AvgIpc    0.022873
17      VSA_EState_variation    0.022768
19       SlogP_VSA_variation    0.019320
8          NumRotatableBonds    0.019045
6   NumAliphaticHeterocycles    0.000000
3                      MolWt    0.000000
2                        SPS    0.000000
21                  balance3    0.000000

In [45]:
selector = SelectKBest(score_func=f_classif, k=2)
X_new = selector.fit_transform(X, y)

# print("Scores for each feature:", selector.scores_)
# print("Selected features:", X.columns[selector.get_support()])

Scores for each feature: [4.39947100e+00 1.20896383e+01 1.20896383e+01 4.07145502e+00
 3.98775437e+00 1.00541787e+01 5.49750432e+00 8.73314141e+00
 9.08863349e+00 8.73795296e+00 8.47170129e+00 1.38242268e+01
 9.54814592e+00 1.01050762e+01 1.26764542e+01 9.79516594e+00
 9.95307639e+00 8.65020358e+00 7.91254865e+00 5.12328845e+00
 8.25562025e+00 5.21541755e+00 6.47280689e+00 8.71752814e+00
 3.77178335e-01 7.97654021e+00 2.19801653e+00 1.45754835e+01
 4.12113503e+00 2.63458210e+00 1.58608499e+00 3.07153913e+00
 7.75616830e+00 1.42630618e+00 1.03151537e+01 1.45055380e+00
 2.27139822e+00 1.44880968e+01 4.15199409e+00 5.63340870e+00
 4.30418160e+00 7.39507201e+00 1.20998174e+00 6.57745354e-01
 3.25804529e+00 1.15817070e+00 1.00000000e+00 8.99157505e-01
 4.86479873e-01 1.52290728e+01 9.10835172e-01 9.10835172e-01
 3.62409256e+00 4.38611149e+00 7.05986729e+00 1.00000000e+00
 8.18383852e+00 3.52779771e+00 7.60356581e+00 2.49365544e+01
 1.71948519e+00 1.55361541e+01 4.86479873e-01 3.33781061e-01
 3.36834971e-01 1.99743232e+01 5.43915756e-02 4.88932612e-02
 4.54804270e+00 8.33717761e-01 1.59050387e+00 1.29389644e+00
 3.21597887e+00 7.42446743e+00 4.02429150e+00 6.87218914e+00
 4.67197944e+00 1.47320370e+01 4.02429150e+00 1.11990146e+01
 3.33781061e-01 1.47853105e-01 3.24095207e-01 4.61846248e+00
 1.10509249e+00 4.22180274e+00 4.16073671e-01 1.10509249e+00
 8.10039932e-02 6.69811321e-01 9.17596081e+00 5.41689373e+00
 4.51566846e+00 0.00000000e+00 5.03291139e-01 2.30709800e+00
 1.59317841e+01 1.59317841e+01 3.04797329e+00 1.94840834e+00
 1.40000000e+01 1.37217007e-01 1.09230769e-01 3.42889996e+00
 3.36834971e-01 1.11911732e-01 1.00000000e+00 1.00000000e+00
 0.00000000e+00 3.01473137e+00 6.85575613e+00 1.29389644e+00
 8.21080050e+00 8.21080050e+00 6.38894502e+00 6.89678656e+00
 1.00000000e+00 6.83935239e+00 7.44121298e+00 1.00000000e+00
 2.21178676e+00 1.14897011e+01 1.14897011e+01 6.85040035e-05
 1.60506886e+01 4.98329854e+00 1.51411481e+01 1.42763546e+01
 7.66967412e-01 1.54304546e+01 8.21080050e+00 8.21080050e+00
 1.92812900e+00 4.51359442e+00 1.00000000e+00 4.77871625e+00
 5.58179430e+00 1.00000000e+00 1.00979325e+01 8.21080050e+00
 8.21080050e+00 3.36136155e-01 8.05002535e+00 7.62420859e+00
 7.75929143e+00 1.70350763e-02 8.21080050e+00 8.21080050e+00
 1.36459276e-01 8.40259312e+00 8.45245742e+00 8.42100444e+00
 2.53363302e-02 6.65705407e+00 6.65705407e+00 6.22264379e+00
 8.65947592e+00 4.10602129e+00 1.01242886e+01 7.23184788e+00
 5.71910980e-01 3.95941627e+00 9.58833346e+00 9.58833346e+00
 8.58830243e+00 9.12698366e+00 9.01780003e+00 9.20103493e+00
 9.31287635e+00 9.48743473e-01 1.85240430e+00 9.38772480e+00
 1.12382850e+01 1.22223785e+01 2.67227242e-04 3.83317023e+01
 7.17302121e+00 6.08587074e+00]
Selected features: Index(['fr_NH2', 'balance4'], dtype='object')

In [37]:
model = LogisticRegression()
selector = RFE(estimator=model, n_features_to_select=2)  # Выбираем 2 лучших признака
selector = selector.fit(X, y)

# print("Selected features:", X.columns[selector.support_])
# print("Feature ranking:", selector.ranking_)

Selected features: Index(['fr_priamide', 'balance4'], dtype='object')
Feature ranking: [  5 115 114 154 165 151  92  39  41  27  67 164 158 157 166 140 142  24
 149  35  57  96 153 108 152 141 132 159 130 161 167 156 145 148 136 135
 131 160 129 127 150  78   7  56  55  88  79  46 118  52  44  54  33  32
  21  68  12  61   9  15  60   4 105  14  42  71  83  93  17  87  75 113
  43  63   2   8  28  16  36  97 103  81  38  20  31  30  37  73  29  50
  23  53  98  48  10  72  13   3 102  19   1  77  47  18  86  40  49  34
  85  45  22  25  58 120 144  89 171 112  84 176  66  95 134 162 104 155
 123 100 175  26  59 124 147  69 172 107  76 177   6  64 119 146  90 109
  80  51  65 121 163  91 110  82  11  70 125 126 117 133 143 101 174  62
  94 128 138 106 137 122  99 173 111 170 169 116  74   1 168 139]

In [39]:
selector = SelectKBest(score_func=mutual_info_classif, k=2)
X_new = selector.fit_transform(X, y)

# print("Scores for each feature:", selector.scores_)
# print("Selected features:", X.columns[selector.get_support()])

Scores for each feature: [0.07305664 0.06804193 0.06728772 0.03962143 0.11356836 0.08024632
 0.09930105 0.08521066 0.05544646 0.08700361 0.11754199 0.09639791
 0.05319989 0.05311808 0.09725571 0.07633233 0.06383251 0.0867596
 0.05918293 0.05900124 0.05983919 0.08012338 0.08276561 0.09119105
 0.1157742  0.08095692 0.07312438 0.0527056  0.07126867 0.02673839
 0.00348278 0.03691108 0.08679353 0.06391673 0.08521223 0.12167419
 0.06828509 0.05110401 0.07246466 0.08046595 0.07848189 0.06852093
 0.         0.00317479 0.         0.00174174 0.         0.01041362
 0.0110354  0.         0.         0.         0.         0.02675275
 0.04939376 0.         0.         0.03928743 0.         0.
 0.03369253 0.01510271 0.         0.00268837 0.00054764 0.00708791
 0.         0.         0.01548776 0.         0.         0.
 0.         0.         0.00098519 0.00502302 0.         0.
 0.         0.01455707 0.02044941 0.         0.0051044  0.
 0.00141321 0.02418726 0.01091237 0.02286568 0.01049434 0.00846597
 0.01448804 0.00449535 0.00844522 0.         0.         0.
 0.00884335 0.         0.0168404  0.         0.00636527 0.
 0.00657805 0.         0.         0.0118963  0.02046757 0.0013107
 0.02659387 0.00544194 0.00724391 0.         0.06573882 0.06600377
 0.04524211 0.04293476 0.01446856 0.06164323 0.05109122 0.00562752
 0.05120335 0.0709937  0.07147618 0.02984674 0.06202315 0.03507307
 0.05566305 0.06815008 0.00183724 0.04373705 0.06559898 0.065997
 0.06103081 0.05162487 0.01394725 0.04644262 0.05727782 0.
 0.07043477 0.06500971 0.06625836 0.04591905 0.06471764 0.05952
 0.07826769 0.06916855 0.0650894  0.06626195 0.05074069 0.08899789
 0.05099505 0.07368267 0.06334024 0.0520306  0.05259289 0.07768656
 0.09678103 0.07551191 0.03103257 0.05539997 0.         0.02985747
 0.02291422 0.02330909 0.0659458  0.0556452  0.10159772 0.04733611
 0.0339961  0.         0.08450285 0.05929494 0.07873894 0.07085388
 0.05154014 0.03885684 0.06081176 0.09085425]
Selected features: Index(['NumValenceElectrons', 'NumRotatableBonds'], dtype='object')

# Подбор гиперпараметров

# Лучшая модель